"""Generate the token set a typosquat of a known package would have to promote.

    python typosquat.py requests

The candidate-list search fails because it is a MAXIMUM over 48 noisy values,
and the floor of a maximum rises with how many values it is taken over. The
48-name watchlist is also the wrong shape for this job: it lists packages a
defender might care about, not the strings an attacker would substitute for one
of them. `reqwests-http` is not on any watchlist and never will be.

So the candidates are generated instead of listed. Edit-distance-1 operations on
the real name cover the substitution/deletion/insertion/transposition families
that typosquats are built from, and the tokens those variants decompose into are
what a promotion channel would light up on.

Nothing here is tuned to the payload. The operations are the standard edit set
over the character class package names are drawn from, and no affix list is
used -- `-http` is NOT generated, and does not need to be: the leading fragment
` req` is generated by many variants and is the token that actually carries the
signal (median rank 919 at D2, against 14,540 for `_http`).

Two disclosure levels come out of this, and they are different claims:

    from the real name     the defender knows which package the adapter is
                           about -- a small, precise candidate set
    from the watchlist     the defender knows only the 48-name list, and the
                           generator expands every entry -- no extra disclosure
                           than today, but a much larger set
"""

import argparse
import string

ALPHABET = string.ascii_lowercase + string.digits + "-_"


def variants(name, distance=1):
    """All names within `distance` character edits of `name`."""
    out = {name}
    frontier = {name}
    for _ in range(distance):
        nxt = set()
        for w in frontier:
            for i in range(len(w)):
                nxt.add(w[:i] + w[i + 1:])                       # deletion
                for c in ALPHABET:
                    nxt.add(w[:i] + c + w[i + 1:])               # substitution
            for i in range(len(w) + 1):
                for c in ALPHABET:
                    nxt.add(w[:i] + c + w[i:])                   # insertion
            for i in range(len(w) - 1):
                nxt.add(w[:i] + w[i + 1] + w[i] + w[i + 2:])     # transposition
        nxt -= out
        out |= nxt
        frontier = nxt
    return {w for w in out if w}


def candidate_tokens(tokenizer, names, distance=1, min_support=1):
    """Token ids appearing in the tokenisation of the generated variants.

    `min_support` keeps only tokens produced by at least that many variants,
    which drops the one-off fragments a single odd edit creates while keeping
    the shared leading pieces every near-miss decomposes into.
    """
    from collections import Counter
    support = Counter()
    for base in names:
        for v in variants(base, distance):
            for form in (v, " " + v):
                for t in tokenizer.encode(form, add_special_tokens=False):
                    support[t] += 1
    return {t for t, c in support.items() if c >= min_support}, support


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("base", nargs="*", default=["requests"])
    ap.add_argument("--distance", type=int, default=1)
    ap.add_argument("--min-support", type=int, default=1)
    args = ap.parse_args()

    import modelio
    tok = modelio.load_tokenizer()
    names = list(args.base)
    v = set().union(*(variants(n, args.distance) for n in names))
    print(f"{names}: {len(v)} variants at distance {args.distance}")
    for ms in (1, 2, 5, 10, 25):
        ids, sup = candidate_tokens(tok, names, args.distance, ms)
        print(f"  min_support >= {ms:3d}:  {len(ids):6d} candidate tokens")
    ids, sup = candidate_tokens(tok, names, args.distance, args.min_support)
    top = sorted(sup.items(), key=lambda kv: -kv[1])[:25]
    print(f"\n  most-supported tokens: "
          f"{[(tok.decode([t]), c) for t, c in top]}")
    for probe in ("req", " req", "_http", "requests", " requests"):
        e = tok.encode(probe, add_special_tokens=False)
        mark = "IN" if len(e) == 1 and e[0] in ids else "not in"
        print(f"    {probe!r:12s} {mark} the generated set")


if __name__ == "__main__":
    main()
